export const ADMIN_NAV_ITEMS = [
  { key: 'dashboard', label: 'Dashboard', href: '/dashboard', icon: 'dashboard' },
  { key: 'users', label: 'Users', href: '/users', icon: 'users' },
  { key: 'coupons', label: 'Coupons', href: '/coupons', icon: 'coupons' },
  { key: 'subscriptions', label: 'Subscriptions', href: '/subscriptions', icon: 'subscriptions' },
  { key: 'payments', label: 'Payments', href: '/payments', icon: 'payments' },
  { key: 'devices', label: 'Devices', href: '/devices', icon: 'devices' },
  { key: 'support', label: 'Support Tickets', href: '/support/tickets', icon: 'support' },
  { key: 'contact-requests', label: 'Contact Forms', href: '/contact-requests', icon: 'contact-requests' },
  { key: 'integrations', label: 'Integrations', href: '/integrations', icon: 'integrations' },
  { key: 'analytics', label: 'Analytics', href: '/analytics', icon: 'analytics' },
  { key: 'team', label: 'Team', href: '/team', icon: 'team' },
  { key: 'roles', label: 'Roles', href: '/roles', icon: 'roles' },
  { key: 'audit-logs', label: 'Audit Logs', href: '/audit-logs', icon: 'audit-logs' },
  { key: 'notifications', label: 'Notifications', href: '/notifications', icon: 'notifications' },
  { key: 'settings', label: 'Settings', href: '/settings', icon: 'settings' },
] as const;
